name = "Craftpicx Evolution Prod"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ee61527fe9c344bd66f550704157a1dba071d0d18ce5c51a3ba72c9a0e0a1d8"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
