name = "Craftpicx Evolution Prod"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e4bebaaa5d7737d7d13d1a3186065635093faa1bfc24c31a121d104dd8caf3e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
