name = "Craftpicx Evolution Prod"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b021175b3403efa1abc03a1d73b7fdd5ff0b6a563ee5614e6bea094dfb03db12"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
